### ISSUE TITLE
Gas Estimation Very Basic Example

### ISSUE THREAD

**Issue by behaviary** [near/devx#253] opened 2020-07-29 22:31 UTC
Requirements:
- Write to collections
- Read from collections
- Expose the transaction to the user
- Output the gas burnt and storage used

Fork simulation test: https://github.com/near-examples/simulation-testing

**Comment by chadoh** [comment] 2020-08-06 21:59
duplicate of #235

**Closed as completed by chadoh** 2020-08-06 21:59 UTC
